apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-recreate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:stable-alpine3.16
        ports:
        - containerPort: 80
  strategy:
    type: Recreate
